name: Check & Build

on:
  schedule:
    - cron: '33 * * * *'
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
      - name: Clone vyos-build repo
        run: |
          cd ~
          git clone https://github.com/vyos/vyos-build.git
          pwd
      - name: Compare Versions
        run: |
          cd ~/vyos-build
          currentVer=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current release determined as $currentVer"
