name: Check & Build

on:
  schedule:
    - cron: '33 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone vyos-build repo
        run: |
          mkdir build
          cd build
          git clone https://github.com/vyos/vyos-build.git
          cd vyos-build
      - name: Compare Versions
        run: |
          currentVer=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current release determined as $currentVer"
