name: VyOS Autobuild Robot

on:
  schedule:
    - cron: '33 * * * *'
  push:
    branches: [ "main" ]

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone hcuk94/vyos-autobuild
        uses: actions/checkout@v3

      - name: Clone vyos/vyos-build
        run: |
          cd ~
          git clone https://github.com/vyos/vyos-build.git

      - name: Find latest release
        id: release
        run: |
          cd ~/vyos-build
          currentVer=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current release determined as $currentVer"
          echo ::set-output name=version::$currentVer


  build-iso:
    if: steps.release.outputs.version == '1.3.2'
    runs-on: ubuntu-latest
    steps:
      - name: Test a thing
          run: echo "nice"